name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t flask-app:latest .
          docker tag flask-app:latest flask-app:latest

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push flask-app:latest

      - name: Deploy Docker Container
        run: |
          docker pull flask-app:latest
          docker stop flask-app_container || true
          docker rm flask-app_container || true
          docker run -d -p 5000:5000 --name flask-app_container flask-app:latest
