name: Python CI/CD
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: >
          docker build -t "${{ secrets.DOCKER_USER }}/flask-app:latest" .

          docker tag "${{ secrets.DOCKER_USER }}/flask-app:latest" "${{
          secrets.DOCKER_USER }}/flask-app:latest"
      - name: Log in to Docker Hub
        run: >-
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{
          secrets.DOCKER_USER }}" --password-stdin
      - name: Push Docker Image to Docker Hub
        run: 'docker push "${{ secrets.DOCKER_USER }}/flask-app:latest"'
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pull Docker image
        run: 'docker pull "${{ secrets.DOCKER_USER }}/flask-app:latest"'
      - name: Stop Existing Container
        run: docker stop flask-app_container || true
      - name: Remove Existing Container
        run: docker rm flask-app_container || true
      - name: Deploy Docker Container
        run: >-
          docker run -d -p 5000:3000 --name flask-app_container "${{
          secrets.DOCKER_USER }}/flask-app:latest"
